# Generated by Django 3.0.6 on 2020-08-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0002_auto_20200828_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
