# Generated by Django 3.0.6 on 2020-08-29 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Configrations', '0003_auto_20200828_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='stars',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='Configrations.Tag'),
        ),
    ]
