# Generated by Django 3.0.6 on 2020-08-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0005_auto_20200828_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(upload_to='static/Blog_Thumbnails'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='static/users'),
        ),
    ]
