# Generated by Django 3.0.6 on 2020-08-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0006_auto_20200830_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
