# Generated by Django 3.0.6 on 2020-09-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0010_auto_20200902_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
