# Generated by Django 3.0.6 on 2020-09-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0011_userhistories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=200, upload_to='users'),
        ),
    ]
