# Generated by Django 3.0.6 on 2020-09-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0012_auto_20200906_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
