# Generated by Django 3.0.6 on 2020-09-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0015_auto_20200908_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistories',
            name='users_following',
        ),
    ]
