# Generated by Django 3.0.6 on 2020-09-08 13:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0016_remove_userhistories_users_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='about_me',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
